### ISSUE TITLE
v0.0.7 keybinding shift-enter does not work anymore

### ISSUE THREAD

**Issue by clojj** [atom-haskell/ide-haskell-repl#11]
after updating to 0.0.7, and Keybindings setting enabled, shift-enter doesn't seem to execute the command anymore.... it simply starts a new line in the repl-input-field without executing the entered input expression

**Comment by lierdakil** [comment]
sorry, what setting?

**Comment by clojj** [comment]
![screen shot 2015-12-08 at 22 53 05](https://cloud.githubusercontent.com/assets/4367963/11669737/7ca2e95a-9dfe-11e5-8508-c8e73c81de6d.png)
![screen shot 2015-12-08 at 22 51 03](https://cloud.githubusercontent.com/assets/4367963/11669675/3a2fd2ae-9dfe-11e5-8986-51b82212862a.png)

**Comment by lierdakil** [comment]
Oh. I forgot about those. I guess I messed up a little. That said, it should work.

Could you check that command palette shows relevant keybinding for `exec command` command? You can find that if you open command palette when repl input field is focused.

**Comment by clojj** [comment]
yep , command-palette shows the key-binding, and selecting the palette-item executes the command normally.
![screen shot 2015-12-08 at 23 01 39](https://cloud.githubusercontent.com/assets/4367963/11669975/b3a801be-9dff-11e5-8b07-fb1a94adca82.png)

Just the keystrokes never get executed

**Comment by lierdakil** [comment]
Well, they should, unless something gets in the way. Could you check with keybinding resolver? (`ctrl-.` by default)

**Comment by clojj** [comment]
top-down:

editor:newline                                    _atom-workspace atom-text-editor:not([mini])_
ide-haskell-repl:exec-command        _atom-text-editor.ide-haskell-repl_

**Comment by lierdakil** [comment]
Well, editor:newline apparently overrides my binding :cry: And it's `ctrl-enter` on Linux. Welp. I guess I'll have to make separate bindings for OSX. You're on OSX, right?

**Comment by clojj** [comment]
right, shouldn't ctrl-enter (as default binding) be fine on OSX too ?

**Comment by lierdakil** [comment]
Any suggestions? `cmd-enter` maybe?

**Comment by clojj** [comment]
cmd-enter would be Ok

**Comment by lierdakil** [comment]
BTW, what about history back/forward? Should I change those as well?

**Comment by clojj** [comment]
don't think so... all the others work right now

**Comment by clojj** [comment]
slightly off-topic, but is it only my impression or does the package-update 'progress-bar' not update itself properly? I have this quite often.
Restart of Atom show updated plugin immediately

**Comment by clojj** [comment]
And thanks for that fix !
works as advertised

**Comment by lierdakil** [comment]
Ok, 0.0.9 should work.

As for progress bar not updating... it happens to me sometimes, but not that often. I found no explanation, and restarting Atom always does fix it, so I don't mind much.

**Comment by clojj** [comment]
you mean 0.0.8 right ?  this works now (0.0.8 is what I received)

**Comment by lierdakil** [comment]
I _actually_ mean 0.0.9. Rushed to publish a little. Shouldn't be any difference on OSX though.
