### ISSUE TITLE
GHCI crashed when open REPL

### ISSUE THREAD

**Issue by rizary** [atom-haskell/ide-haskell-repl#12]
Hi, 

in my OS X, I already install the REPL and change its setting to = 
commandArgs : ghci
mandpath is when i put stack on my folder bin. Inside bin is cabal, ghci, ghc and stack.

the error is:

GHCI crashed
TypeError: Cannot read property 'stdin' of undefinedGHCI crashed
Error: spawn EACCES

**Comment by lierdakil** [comment]
Please post your settings so that I could better understand what is going wrong.

**Comment by rizary** [comment]
in atom : 
Command Args = ghci
Command Path
/Users/Username/ManualHaskell/ghc/bin/

is it correct?

**Comment by lierdakil** [comment]
'Command Path' needs to specify full path to executable, not directory that contains it. 'Command Args' are additional arguments to be passed to said executable.
If you want to use plain `ghci`, you need to set 'Command Path' to something like `/Users/Username/ManualHaskell/ghc/bin/ghci` (this is an educated guess, mind), and you can leave 'Command Args' with default (i.e. empty).
That said, you will probably have better luck using `cabal repl`

**Comment by rizary** [comment]
I tried to change it to /Users/Username/ManualHaskell/ghc/bin/stack but when i start repl it didn't show anything. Is it supported with stack?

**Comment by lierdakil** [comment]
Okay, with stack use 'ghci' in 'command args'
26 дек. 2015 г. 5:42 пользователь "Andika Demas Riyandi" <
notifications@github.com> написал:

**Comment by rizary** [comment]
Ok, 

I have added ghci in 'command args', then i also changed '/Users/Username/ManualHaskell/ghc/bin/stack'

when i open the REPL, it opens a second and then closed.

where can i find the log anyway?

**Comment by lierdakil** [comment]
Just released v0.0.11. It logs errors in dev. console (View → Developer → Toggle Developer Tools)

**Comment by rizary** [comment]
after the last update i got the error on repl tab, it says:

No compiler found, expected minor version match with ghc-7.10.2 (x86_64) (based on resolver setting in /Users/Username/Programming/Haskell/learnHas/stack.yaml).
Try running "stack setup" to install the correct GHC into /Users/Username/.stack/programs/x86_64-osx/

however, on my os x, i am using default ghc path which I installed manually and by default my stack use ghc on my path. In the report, it seems that the ghc must be installed on using stack setup.

if i run stack ghci on my terminal, it still works and no error.

**Comment by lierdakil** [comment]
try running Atom with `stack exec atom`. This seems to be an environment issue.

**Comment by rizary** [comment]
Ahh... thank you it works. thanks for your explanation, finally i understand.
