### ISSUE TITLE
Auto-scroll

### ISSUE THREAD

**Issue by foxeed** [atom-haskell/ide-haskell-repl#17]
Is auto-scroll broken or just currently absent? When I fill up the entire screen with anything („:?“ for example), focus doesn't appear on the bottom of an output, like it normally should.

**Comment by lierdakil** [comment]
A screenshot illustrating the problem might be good. I'm not entirely sure I understand just from your explanation.

**Comment by foxeed** [comment]
It works now, and I didn't touch anything. Terribly sorry for making a ticket about this.
