### ISSUE TITLE
~ doesn't work in Command Path

### ISSUE THREAD

**Issue by simonmichael** [atom-haskell/ide-haskell-repl#21]
In settings -> Command Path, users who have upgraded their stack and don't trust that just "stack" will work, may type ~/.local/bin/stack, in which case the REPL window does not open. With "stack" or an absolute path, it works. Could ~ be supported also ?

**Comment by lierdakil** [comment]
Shell-specific substitutions are not supposed to work. Use absolute paths, or add `$HOME/.local/bin` to PATH.

**Comment by simonmichael** [comment]
$HOME doesn't work either; only an absolute path or (if $PATH is right) "stack" works here.

**Comment by simonmichael** [comment]
So, if it's not fixable, consider at least adding a warning to the field description that we should not use $HOME or ~. 

Also, two other usability items, sorry for adding them here: 
- it would be clearer for Command Path to be the first field and Args the second
- changes in the settings don't affect an open REPL pane, you have to close it and open a new one (if it's not fixable, a warning would be good)

**Comment by lierdakil** [comment]
Yes, I know environment variables substitutions don't work in settings. As I said, you can add said directory to PATH, either using shell facilities, or via Atom's init script similar to this:

``` coffeescript
{sep, delimiter} = require "path"
process.env.PATH = "#{process.env.HOME}#{sep}.local#{sep}bin#{delimiter}" + process.env.PATH
# sep = '/' and delimiter = ':' on POSIX-compatible systems.
# Not so on Windows.
```

**Comment by lierdakil** [comment]
I plan to eventually remove this option altogether in favour of ide-haskell-wide PATH setup. So I don't really see much value in fiddling with descriptions at this point. I will accept a PR though.

**Comment by lierdakil** [comment]
See https://github.com/atom-haskell/ide-haskell-repl/blob/master/lib/ide-haskell-repl.coffee

**Comment by lierdakil** [comment]
> changes in the settings don't affect an open REPL pane, you have to close it and open a new one (if it's not fixable, a warning would be good)

It is "fixable", but that would require repl session restart anyway. So I opted to let user decide if they want to restart session themselves or not. I assumed that's rather obvious, given you're changing invocation settings.

**Comment by lierdakil** [comment]
> it would be clearer for Command Path to be the first field and Args the second

Fixed in master. I will hold off on release in case you want make a PR wrt setting descriptions.

**Comment by simonmichael** [comment]
Ok, sounds good. No, it wasn't obvious that the setting change wouldn't affect the open REPL pane (I'm new to Atom, and some other settings seemed to have immediate effect). 

I failed to get this working on last attempt, but figured it out today. Thanks for your work to improve the haskell IDE setup experience.
