### ISSUE TITLE
Console screen doesn't scroll down automatically on new content

### ISSUE THREAD

**Issue by varosi** [atom-haskell/ide-haskell-repl#23]
That way when content is more than single page I have to scroll it by hand on each command.

Windows 10

**Comment by masimun** [comment]
I have the same issue.

**Comment by lierdakil** [comment]
Let me know if it doesn't work in 0.0.23.

**Comment by masimun** [comment]
This issue is resolved now, thanks

**Comment by emaphis** [comment]
Works for me also, thanks

**Comment by varosi** [comment]
It scrolls down, but every time I open REPL there are opened two same REPL
windows, instead of one.

On Windows 10

2016-05-30 17:24 GMT+03:00 Ed Maphis notifications@github.com:

**Comment by varosi** [comment]
After restart after update - it is working fine with single REPL.

Thank a lot!

2016-05-31 0:17 GMT+03:00 Vassil Ognyanov Keremidchiev varosi@gmail.com:
