### ISSUE TITLE
A way to set REPL arguments in Settings

### ISSUE THREAD

**Issue by varosi** [atom-haskell/ide-haskell-repl#24]
It would be very useful for arguments, like "-fbreak-on-exception". Not to set them each time REPL is executed.

**Comment by lierdakil** [comment]
Um. Set commandArgs to something like `repl, -fbreak-on-exception`. Bear in mind that breaks can errm... break ide-haskell-repl.

**Comment by varosi** [comment]
Thanks! I didn't know about commas and tried directly without them. May be it will be more intuitive to get only first word as executable and all the rest as arguments?

This is working right for Stack:

> repl, --ghci-options, -fbreak-on-exception
