### ISSUE TITLE
Option to reverse Enter with Shift+Enter

### ISSUE THREAD

**Issue by varosi** [atom-haskell/ide-haskell-repl#25]
Most of operations I enter in REPL are single line and it will be more efficient for me to use only Enter for single line command execution and Shift+Enter for multi-line.

**Comment by lierdakil** [comment]
You can do that yourself via keymap rebinding. Open your keymap (via edit menu) and do:

``` cson
'.platform-win32 atom-text-editor.ide-haskell-repl':
  'enter': 'ide-haskell-repl:exec-command'
  'shift-enter': 'editor:newline'
```

That's assuming you're on win32.

**Comment by varosi** [comment]
Great! Thanks! Now it is much logical for me.
