### ISSUE TITLE
Only one line is printed to the output buffer

### ISSUE THREAD

**Issue by masimun** [atom-haskell/ide-haskell-repl#26]
If there is a trace statement (Debug.Trace) the output of the trace is not printed to the repl.

**Comment by lierdakil** [comment]
Repl doesn't show stderr (to which Debug.Trace outputs stuff). You can check stderr if you open Atom's developer console.

Long story short, since all ghci errors end up on stderr, it'd be problematic to figure out what your intent was in the first place.
