### ISSUE TITLE
Auto Reload Repeat Feature

### ISSUE THREAD

**Issue by theGhostJW** [atom-haskell/ide-haskell-repl#27]
It would be really helpful to have a command that could be bound to a keyboard shortcut from the Haskell editor that would invoke a reload then re-execution of  the last command run by the repl. Even better if it could optionally be configured to auto-rerun on save.

**Comment by lierdakil** [comment]
Done in v0.3.0, see package commands and settings.

**Comment by theGhostJW** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! FREAKING AWESOME !!!!!!!!!!!!!!!!!!!!
