### ISSUE TITLE
`stack ghci` integration

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/ide-haskell-repl#3]
Maybe this relates to the development of a stack backend separate from cabal backend, but anyway, an integrated repl based on `stack ghci` would be ideal for Stack-based projects.

**Comment by lierdakil** [comment]
You can configure this package to use stack ghci.
31 окт. 2015 г. 5:29 пользователь "Aaron Wolf" notifications@github.com
написал:

**Comment by wolftune** [comment]
okay cool. The way that is done seems a little clunky (setting `ghci` first and then `stack` later), but I understand this is a work in progress. I hope it will support tab-completion eventually. Nice work overall. I'll be patient to see this evolve.
