### ISSUE TITLE
Command edit control becomes unusable when it does not fit a command

### ISSUE THREAD

**Issue by vasily-kirichenko** [atom-haskell/ide-haskell-repl#30]
![screenshot from 2016-09-12 17-52-22](https://cloud.githubusercontent.com/assets/873919/18440457/41820624-791a-11e6-8048-7050602ca58d.png)

I think the control should enlarge its height automatically (becoming N-lines control) in this case.

**Comment by lierdakil** [comment]
Well, your scrollbars are huge, but I understand that's not the main issue here. You can toggle soft line-wrap with `Editor: Toggle Soft Wrap` command from command palette (you can also bind it to a hotkey if you wish). 

I agree that this should be enabled by default. Which it is in 0.1.4. Thanks for pointing that out.

**Comment by vasily-kirichenko** [comment]
Great, it works nicely now. Thanks!
