### ISSUE TITLE
REPL does not respect extended formatting

### ISSUE THREAD

**Issue by vasily-kirichenko** [atom-haskell/ide-haskell-repl#31]
Trifecta library formats errors in GHCi like this:

![screenshot from 2016-09-25 20-35-34](https://cloud.githubusercontent.com/assets/873919/18817066/a49be370-835f-11e6-8c43-10445dfc4588.png)

Haskell IDE REPL does it like this:

![screenshot from 2016-09-25 20-36-33](https://cloud.githubusercontent.com/assets/873919/18817069/c39a8786-835f-11e6-84e8-b2c895843c9b.png)

**Comment by lierdakil** [comment]
Thank you for your report. Sadly, there's not much I can do in terms of terminal formatting support save from writing a terminal emulator (which I _won't_ do for various reasons). I'm not sure if you can disable this formatting library-side somehow (environment variables? package options?). If you can, I suggest either doing that, or letting me know how that works so I could implement that package-side. If you can't, I'll see if I can filter terminal control sequences out of output. But that might take a little while, I'm still extremely short on time, and likely will be for a couple more weeks.

**Comment by vasily-kirichenko** [comment]
Filtering the formatting out would be totally OK. I'm not familiar with linux, so I've no idea how such formatting works :(

**Comment by lierdakil** [comment]
Okay, v0.3.1 should filter out ANSI escape sequences. Let me know if it works for you.
