### ISSUE TITLE
On Windows the Repl plugin gets confused by whitespace

### ISSUE THREAD

**Issue by mrakgr** [atom-haskell/ide-haskell-repl#33]
```
<no location info>: can't find file: C:/Various%20Exercises/asd.hs
```

Copied verbatim from the output. Replacing the %20 (space) with an underscore makes the problem go away.

**Comment by lierdakil** [comment]
See if v0.1.6 fixes this.

**Comment by mrakgr** [comment]
I can confirm that it loads fine now, but inside the atom tab control's header, the text shows up as `REPL: C:/Various%20Exercises/asd.hs` with the whitespaces showing as %20. It would be nice if this could be fixed.

**Comment by lierdakil** [comment]
Hmm. Actually, I don't think I should fiddle around with uris, looking at Atom source. What version are you using?

**Comment by lierdakil** [comment]
Version of Atom that is

**Comment by mrakgr** [comment]
1.10.2. It says that it is up to date.

**Comment by lierdakil** [comment]
Okay, I figured it out. 0.1.7 should be fine.

**Comment by mrakgr** [comment]
No, not quite. The header shows up fine and the modules load and execute fine inside the REPL, but on startup it gives an error like this `Couldn't read "\"C:\\!Various Exercises\\Haskell Exercises\\test.hs\""as String`.

**Comment by lierdakil** [comment]
Uh... could you run something like `:load "C:\!Various Exercises\Haskell Exercises\test.hs"` in ghci for a quick sanity check?

**Comment by mrakgr** [comment]
```
C:\!Various Exercises>ghci
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Prelude> :load "C:\!Various Exercises\Haskell Exercises\test.hs"
Couldn't read "\"C:\\!Various Exercises\\Haskell Exercises\\test.hs\""as String
Prelude>
```

**Comment by lierdakil** [comment]
Huh. That's unexpected. Okay. And I would assume that goes away once you escape backslashes, e.g. `:load "C:\\!Various Exercises\\Haskell Exercises\\test.hs"`?

**Comment by mrakgr** [comment]
```
Prelude> :load "C:\\!Various Exercises\\Haskell Exercises\\test.hs"
[1 of 1] Compiling Main             ( C:\!Various Exercises\Haskell Exercises\test.hs, interpreted )
Ok, modules loaded: Main.
*Main>
```

**Comment by lierdakil** [comment]
Okay, this took a lot more effort than I expected, but 0.1.8 should work. Can you confirm?

**Comment by mrakgr** [comment]
Yeah, it works fine now. Thank you very much.
