### ISSUE TITLE
Empty string is outputted before any result

### ISSUE THREAD

**Issue by vasily-kirichenko** [atom-haskell/ide-haskell-repl#35]
![screenshot from 2016-10-10 20-54-07](https://cloud.githubusercontent.com/assets/873919/19245793/b64b56a0-8f2b-11e6-9cd2-eca1f8703a97.png)

Ubuntu, 0.1.10

**Comment by lierdakil** [comment]
1) Can't repro
2) It's not output, but rather input. It seems like `ide-haskell-repl:exec-command` gets run twice in rapid succession. Check your keybindings or whatever.

**Comment by vasily-kirichenko** [comment]
Cannot reproduce after Atom was restarted.
