### ISSUE TITLE
Repl window is not restarted after update to new version of ide-haskell-repl plugin

### ISSUE THREAD

**Issue by varosi** [atom-haskell/ide-haskell-repl#39]
After update "Open REPL" command is gone, too. I have to restart whole Atom.

**Comment by lierdakil** [comment]
This is likely a bug (or maybe lack of feature) in Atom. Long story short, you need to open at least one Haskell file for package to actually activate after update.

**Comment by varosi** [comment]
Ah, okay, just I noticed that. You could close that issue then if you decide.
