### ISSUE TITLE
Compilation error field is to narrow

### ISSUE THREAD

**Issue by opudalo** [atom-haskell/ide-haskell-repl#40]
Compilation errors are not readable 
<img width="632" alt="screen shot 2016-11-07 at 9 26 31 am" src="https://cloud.githubusercontent.com/assets/775750/20069161/4ddfe4ea-a4d0-11e6-8465-05c22d382d7d.png">

**Comment by lierdakil** [comment]
I'm sorry, but what else do you expect from 'Variable not in scope' error? The field will expand if there's more output.

**Comment by lierdakil** [comment]
![image](https://cloud.githubusercontent.com/assets/7275622/20311551/482eda6e-ab61-11e6-8241-e619911fb4af.png)

**Comment by opudalo** [comment]
@lierdakil Sorry, my description was not too accurate.
The field becomes smaller and smaller with each next call.
It took me throw an error about 20 times (just repeat `:l Main` command) to go from full view to very narrow.

**Comment by opudalo** [comment]
<img width="632" alt="screen shot 2016-11-15 at 9 32 28 am" src="https://cloud.githubusercontent.com/assets/775750/20316534/1a9082dc-ab17-11e6-8fa0-d6319eb7461b.png">
<img width="641" alt="screen shot 2016-11-15 at 9 34 10 am" src="https://cloud.githubusercontent.com/assets/775750/20316537/1d00bb7c-ab17-11e6-98db-c3566845db06.png">
<img width="652" alt="screen shot 2016-11-15 at 9 34 35 am" src="https://cloud.githubusercontent.com/assets/775750/20316544/2257c4e4-ab17-11e6-95da-687a78971f71.png">

**Comment by lierdakil** [comment]
Okay, now I see the issue. Should be fixed with v0.4.6.
