### ISSUE TITLE
Integrate with HyperHaskell

### ISSUE THREAD

**Issue by ggreif** [atom-haskell/ide-haskell-repl#41]
https://github.com/HeinrichApfelmus/hyper-haskell is a graphical frontend also based on Electron.

**Comment by lierdakil** [comment]
I've looked over, and I don't think it's simple. You could probably adapt h-h frontend to work as an Atom package though, but that's not a project I'm thrilled to dive into at this point. In any case, doesn't have much to do with ghci frontend.

If someone wants to give it a shot, feel free to pick this up.
