### ISSUE TITLE
On Windows haskell-repl chrashes on startup

### ISSUE THREAD

**Issue by ghost** [atom-haskell/ide-haskell-repl#47]
Hello, 

I installed this package with this settings : 

- default repl :  ghci 
- stack path : C:\Users\rwobb\AppData\Roaming\local\bin\stack
- cabal path : empty 
- ghci path : C:\Users\rwobb\AppData\Roaming\local\bin\ghc-mod legacy-interactive
- extra args : empty 
ghci wrapper : empty 
auto reload : not selected 

When I look at the developers pane I see not errors. 

Still when I do open repl, I see the repl and then it disappeared

**Comment by lierdakil** [comment]
`ghci path : C:\Users\rwobb\AppData\Roaming\local\bin\ghc-mod legacy-interactive`? that's not right... if you're using stack exclusively, leave `ghci path` empty and set `default repl` to `stack`

**Comment by ghost** [comment]
Thanks, everythings works fine now

**Comment by piratdit** [comment]
Hi, 

I am facing a similar issue.

When I open ide-haskell-repl, nothing happens.
I have an open haskell file and open the repl, but the repl pane is empty. 
And it doesn't show any errors in the pane.
I can write in the repl pane, but nothing happens regardless of what I type.
Haskell _works_ elsewhere on the computer, I can compile and run haskell files via the command line

OS: Windows 10

Haskell ver: Haskell Platform 8.2.1

Atom ver: Latest

Settings: 
default repl : stack
stack path : C:\Users\MYUSER\AppData\Roaming\local\bin\stack

Do you have any idea why? Am I missing some dependecies? Is there an error log somewhere?

I also use this: https://github.com/Tehnix/atom-haskell

![repl](https://user-images.githubusercontent.com/3216119/30201691-fa8e9038-947b-11e7-958c-a234a7945429.PNG)

**Comment by lierdakil** [comment]
@perrosvik, it would seem ghci isn't started for one reason or another. You could check dev. console for error messages (View -> Developer -> Toggle Developer Tools -> Console tab)

**Comment by lierdakil** [comment]
@perrosvik, sorry it took so long, should be fixed in v0.7.2.

**Comment by piratdit** [comment]
No worries, I haven't had the time to tinker with Atom and Haskell these past weeks, but I will check out the new version.
