### ISSUE TITLE
Autocomplete ignores Enter key while loading

### ISSUE THREAD

**Issue by chrismwendt** [atom-haskell/ide-haskell-repl#51]
Hitting Enter in the REPL doesn't work when autocomplete is still loading the suggestions:

![kapture 2017-05-06 at 15 15 21](https://cloud.githubusercontent.com/assets/1387653/25775970/02201232-326f-11e7-91f2-64a071fad4f2.gif)

It's hard to see, but I typed `T` then `o` then `<Enter>` and the line didn't get submitted to GHCi. However, `<Enter>` worked after waiting a few seconds.

**Comment by lierdakil** [comment]
Well, not something we can avoid, since autocompletion is handled by GHCi as well, and the interface is synchronous, i.e. if it's spitting out suggestions, it can't do anything else...

**Comment by lierdakil** [comment]
Fixed in v0.7.13 or somewhere near (and actually would've been sooner if not for a bug in implementation). Now commands get sent into a queue instead of being rejected outright.
