### ISSUE TITLE
I can't type anything in the REPL

### ISSUE THREAD

**Issue by etorreborre** [atom-haskell/ide-haskell-repl#52]
Hi, I don't know what I did wrong (I'm new to Atom) but I can't seem to be able to edit anything with the REPL:

![image](https://user-images.githubusercontent.com/10988/31047220-c0c21446-a606-11e7-9b34-ea0ca97995af.png)

The panel is greyed out which I think means it's not fully initialized?

And the REPL messages in ide-haskell show:
```
Did not find .cabal file for hjsonpointer-1.2.0 with Git SHA of 42588498219488475d395388fd77b42a1539098d
specs-0.1.0.0: unregistering (local file changes: src/Streaming/Producer.hs test/Test/Streaming/Producer.hs)
specs-0.1.0.0: configure (lib + exe)
Configuring specs-0.1.0.0...
specs-0.1.0.0: initial-build-steps (lib + exe)
Configuring GHCi with the following packages: specs
Using main module: 1. Package `specs' component test:specs-test with main-is file: /Users/etorreborre/projects/haskell/specs/test/test.hs
```
I wonder if the first message is problematic or not. 

Thanks for your help!

PS: I'm using the most recent version of everything + stack as my builder

**Comment by lierdakil** [comment]
Uh... You seem to be under the impression that you can type something in the main window. This is not the case. The input field is below the prompt.
![image](https://user-images.githubusercontent.com/7275622/31054114-42bf91f0-a6b4-11e7-970c-a3d80661fa2f.png)
^--- here
Then you use `ide-haskell-repl:exec-command` to send whatever you typed to execution (`shift`+`enter` by default on Windows and Linux, `cmd`+`enter` on OSX).

**Comment by etorreborre** [comment]
Silly me, I was just not typing in the right place, thanks for the fast answer!

**Comment by jxsv** [comment]
Is there any way to activate the input line without mouse? When switching to REPL pane using keyboard shortcuts the input line is not active, which should be by default in my opinion ...
