### ISSUE TITLE
Question :  How can I use this in a repl 

### ISSUE THREAD

**Issue by ghost** [atom-haskell/ide-haskell-repl#53]
Hello, 

I make the challenges of the haskell book of bitemyapp. 

There I made this code : 

```
Module Lib  where

import Data.Monoid

data Optional a = Nada
                | Only a
                deriving (Eq, Show)

instance Monoid a => Monoid (Optional a) where
  mempty                     = Nada
  mappend Nada (Only x)      = Only x
  mappend (Only x) Nada      = Only x
  mappend (Only x) (Only y)  = Only (x <> y)

```

Now I want to test it in repl with : 

`Only (Sum 1) `mappend` Only (Sum 1)`

How can I send this to the repl in Windows. I tried crtl + enter but nothing happens 

Roelof

**Comment by lierdakil** [comment]
Default keybindings: https://github.com/atom-haskell/ide-haskell-repl/blob/master/keymaps/ide-haskell-repl.cson

You probably want `exec-command` which is bound to `shift`+`enter` by default on win32.
