### ISSUE TITLE
Input line inactive on REPL pane activation

### ISSUE THREAD

**Issue by jxsv** [atom-haskell/ide-haskell-repl#56]
Starting with version 0.7.0, on activating pane with haskell-repl the input line is not activated by default, one has to click in the input line to enter commands.
Thanks for your work on this package!

**Comment by lierdakil** [comment]
Thanks for reporting. Hopefully fixed in v0.7.7, but it's a little tricky, so let me know if it doesn't work.

Note: v0.7.7 requires Atom v1.22 or newer.

**Comment by jxsv** [comment]
Unfortunately, the behavior is the same with 0.7.8 for me.

**Comment by lierdakil** [comment]
Okay... try v0.7.9 then, that one might work better...

**Comment by jxsv** [comment]
0.7.9 fixes the issue!

**Comment by lierdakil** [comment]
Great! I'll be closing this then.
