### ISSUE TITLE
REPL does not see debug state

### ISSUE THREAD

**Issue by tblnx** [atom-haskell/ide-haskell-repl#6]
When I start Haskell Repl, I can set breakpoints and start de application. When a breakpoint is reached, the app stops, but within Atom nothing is to be seen. E.g. :list says no breakpoint has been reached.
I use Atom 1.2.4, the plugin says 1.0.0 followed by 3.3.9 on Kubuntu 14.04
From a terminal everything works as expected.

**Comment by lierdakil** [comment]
Sorry about late reply. To tell you the truth, this was never intended as a debug utility, so I have no idea why this happens or how to fix it. Sorry. I will try to take a look when I have some spare time, but that might not happen until next year.

**Comment by tblnx** [comment]
Op dinsdag 8 december 2015 11:58:43 schreef Nikolay Yakimov:

**Comment by lierdakil** [comment]
This should, in general, work by now. If not, please open new issues. Thank you.
