### ISSUE TITLE
Repl inputs not being written to its history

### ISSUE THREAD

**Issue by freeman42x** [atom-haskell/ide-haskell-repl#61]
How to reproduce:

```Haskell
module Ch13 where

import Control.Monad
import System.IO (hSetBuffering, stdout, BufferMode(..))
import System.Exit (exitSuccess)
import Data.Char (isLetter, toLower)

-- Madam I’m Adam,

palindrome :: IO ()
palindrome = do
  hSetBuffering stdout NoBuffering
  forever $ do
    line <- getLine
    if isPalindrome line
      then do
        putStrLn "It's a palindrome!"
        exitSuccess
      else putStrLn "Nope!"

isPalindrome :: String -> Bool
isPalindrome s = sm == reverse sm
  where
    sm = toLower <$> filter isLetter s
```

Load the module in the repl with `:l`
Type `palindrome` and <enter>
Type anything. Whatever you typed will not be written to the REPL history. If the `Interrupts current computation` button is pressed then the strings typed will appear in the history.

Expected behavior (repl run from terminal):

> *Ch13> palindrome 
> qwe
> Nope!
> nqwejbqwe
> Nope!
> Madam I'm Adam
> It's a palindrome!
> *** Exception: ExitSuccess

**Comment by lierdakil** [comment]
Thanks for reporting. So v0.7.12 shows stdin input straight away, that was a bug.

There's one caveat though. When sending text to stdin, there is no implicit newline, so you need to deliberately add a line to any input before (or after) sending it.

I.e. running
```
palindrome
```
then
```
qwe
```
will literally send `qwe` with no trailing newline to stdin, so `getLine` won't yield at this point.

Sending
```
qwe

```
or
```
qwe
```
then
```

```
(literally just newline by itself)
will work more or less as you would expect.

That's a bit of a limitation of the chosen execution model that doesn't send input immediately as you type it. The point is to allow sending stdin that doesn't end with a newline (which is possible in terminal)

An alternative to that is implementing a terminal emulator in javascript, which isn't something I'm keen on doing.

While on topic, there's another caveat: sending multiple input lines can potentially spill into the command context, f. ex. running
```
getLine
```
then sending
```
asd
:q

```
will actually kill the REPL session. That's something that might need some work, but I'm not entirely sure how to go about it.

**Comment by freeman42x** [comment]
Not sure if related but sometimes I type REPL commands and they are not being shown on screen and neither their result. I noticed that when I get autocomplete for them it always works. And besides the fact that the command is not being run - it is not in the command history either. Seems like the repl is sometimes in a state in which it does not accept commands and it is not always obvious to tell.

**Comment by lierdakil** [comment]
Not related, but I think I might know why. Tried to fix. Open a new issue if this persists with v0.7.13.

Anyway, I'm closing this, let me know if the original issue isn't resolved in the latest release.
