### ISSUE TITLE
<Reload Repaet On File Save> is not always updating the exception panel

### ISSUE THREAD

**Issue by theGhostJW** [atom-haskell/ide-haskell-repl#64]
1. write a simple hunit test that passes 
2. run in REPL
=> passes - no exception message
3. activate <reload repeat on file save> button
4. change test to make it fail and save
=> HUnit exception message displayed in console panel above input as expected
5. restore the test to a passing state and <Save>
=> Exception is still displayed with error message as if test is still failing
6. click the **( ! )** reload repeat button
=> Exception panel is hidden correctly indicating test is passing

Note: in may take a few toggles of the test in and out of a failing state + <save> to surface this behavior. It doesn't always happen first time. Sometimes the behavior is reversed (i.e. test is failing but error panel not showing an HUnit exception)  

note:  Windows 10

**Comment by lierdakil** [comment]
There's a simple explanation for that: REPL messages are forcibly persisted for a short duration (~ 10 seconds to be exact), otherwise, you might miss some of those.

Maybe clearing those out on reload would be a solution.

**Comment by theGhostJW** [comment]
Sounds good.

By waiting > 10 seconds between toggling tests the issue does not occur which is confirms your point. 

 I have also noticed that clearing messages [trash can button] does not clear the repl message panel.  So maybe clearing REPL message on message clear should also be added.

**Comment by lierdakil** [comment]
v0.7.15 implements both suggestions. Note that as a side effect clearing output will also clear errors reported by REPL (which might be a good thing actually)

**Comment by theGhostJW** [comment]
FIXED !!!!!!!!!!!!!! :-)
