### ISSUE TITLE
module `main:*' is defined in multiple files

### ISSUE THREAD

**Issue by freeman42x** [atom-haskell/ide-haskell-repl#66]
I started getting this error in the REPL tab. Not sure how to reproduce it as it always happens. ide-haskell-repl v. 0.8.0

    <no location info>: error:
        module `main:Ch21' is defined in multiple files: src/Ch21.hs
                                                         src/Ch21.hs

**Comment by lierdakil** [comment]
GHC version? Also do you run REPL via stack, cabal-install, or just plain GHCi?

**Comment by freeman42x** [comment]
GHC 8.2.2
running REPL via stack
At one point I have seen 2 of those errors at the same time for different files.

**Comment by freeman42x** [comment]
This was an issue caused by `.ghci` configuration I added for using GHCID https://github.com/ndmitchell/ghcid
