### ISSUE TITLE
Chasing arrows' state color not restored across restarts

### ISSUE THREAD

**Issue by ggreif** [atom-haskell/ide-haskell-repl#69]
When I click into the chasing arrows icon to activate it (green), all is nice.
Restart `atom` and observe that the greenness is gone.

However the functionality is fine. Saving re-runs the last command/expression in repl.

Clicking into the icon has no effect in color (remains grey), but now the re-run on save functionality is disabled.

At this point everything is in consistent state again.

**Comment by lierdakil** [comment]
Should be fixed in v0.8.2. Sorry for the delay.

**Comment by ggreif** [comment]
Confirmed. Thanks!
