### ISSUE TITLE
Command error permanently covers part of repl output

### ISSUE THREAD

**Issue by SecondReality** [atom-haskell/ide-haskell-repl#7]
Atom Version: 1.2.4
System: Microsoft Windows 7
package version: 0.0.4

Command error permanently covers part of repl output.

Reproduction:
1: Do a command that gives a lot of error text in the bar above the input field.
2: Do a command that gives shorter (or no) error text in the bar above the input field

After this an empty area covers part of the repl text output pane, making it hard to see new output.

It doesn't happen every time so I'll look more into exact reproduction steps.

**Comment by lierdakil** [comment]
Not sure what might cause it. Any insight is appreciated.

**Comment by lierdakil** [comment]
Actually, I was planning to use ide-haskell for warning output anyway. So v0.0.7 does just that. Hopefully, this resolves this problem.
