### ISSUE TITLE
Warning message after loading REPL: Some flags have not been recognized: prompt2

### ISSUE THREAD

**Issue by freeman42x** [atom-haskell/ide-haskell-repl#74]
Full warning message:

> REPL: /home/neo/Projects/haskell-editor-setup/src/Util.hs
<interactive>: repl: Some flags have not been recognized: prompt2, 

![image](https://user-images.githubusercontent.com/1758708/79392104-b4838300-7f6a-11ea-9deb-efac37d903b4.png)

I do not have any `.ghci` which would set prompt2, so I do not understand why it gives that error.

**Comment by lierdakil** [comment]
Basically, GHC introduced `prompt2` at some point. Then they renamed it to `prompt-cont`. Then I had the displeasure of fumbling around with supporting both. Probably a good idea to filter out those specific warnings, but I honestly started to ignore those after a little while, so never got to filtering those out.

**Comment by freeman42x** [comment]
@lierdakil could you filter out this message please? It is quite distracting to me

**Comment by lierdakil** [comment]
Should be fixed in v0.9.6

**Comment by freeman42x** [comment]
Thank you so much!
