### ISSUE TITLE
Feature request: Checkbox for Alt-Enter on Settings page

### ISSUE THREAD

**Issue by SecondReality** [atom-haskell/ide-haskell-repl#8]
Shift-Enter isn't intuitive for some users, and multiline text is rarely needed.
It would be nice if we could default to enter to input text, or have an option on the settings page.

(I wasn't sure if I should put feature requests here, let me know if I'm out of line!)
(also I'm a fan of the repl, I might work on some of these)

**Comment by lierdakil** [comment]
0.0.5 Made all shortcuts rebindable. See updated readme for more info.
